import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import HomeContextProvider from "./context/HomeContext";

const poppins = Poppins({
  weight: ["100", "500", "700", "900"],
  subsets: ["latin"],
  variable: '--font-poppins'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <HomeContextProvider>
      <html lang="en">
        <body className={poppins.variable}>{children}</body>
      </html>
    </HomeContextProvider>
  );
}
